name: ML CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training
      run: |
        python src/train.py

    - name: Upload trained models
      uses: actions/upload-artifact@v4
      with:
        name: fake-news-model
        path: models/
